-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2024. Dec 06. 13:38
-- Kiszolgáló verziója: 10.4.28-MariaDB
-- PHP verzió: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `esemenyek`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `esemeny`
--

CREATE TABLE `esemeny` (
  `id` int(11) NOT NULL,
  `nev` varchar(255) NOT NULL,
  `datum` varchar(255) NOT NULL,
  `varosid` int(11) NOT NULL,
  `tipusid` int(11) NOT NULL,
  `leiras` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `esemeny`
--

INSERT INTO `esemeny` (`id`, `nev`, `datum`, `varosid`, `tipusid`, `leiras`) VALUES
(597, 'Keceli Virágfesztivál 2024. FLORA Virágfesztivál és Keceli Országos Fazekas Kiállítás', '2024. december 6. (péntek) - 2024. december 8. (vasárnap) ', 140, 1, 'Kecelen a FLORA Virágfesztivál 2024. december 6-8. között kerül megrendezésre. A  rendezvényre az ország minden tájáról érkeznek virágkötők, virágtermelők, fazekas- és népi mesterek, hogy virágkölteményeikkel és nívós munkáikkal bemutatkozzanak a nagyközö'),
(598, 'Gyulai Mézfesztivál 2024', '2024. december 14. (szombat) - 2024. december 15. (vasárnap) ', 106, 1, '15. Gyulai Mézfesztivál 2024. december 14-15-én. Ezen a hétvégén minden az édes finomságról és a méhészetről szól. A látogatók megismerkedhetnek a méhészettel és a mézkészítéssel is, melyről sok hasznos és érdekes információt tudhatnak meg a szakmai napon'),
(599, 'Gyulai fesztiválok 2024 / 2025', '2024. december 14. (szombat) - 2024. december 15. (vasárnap) ', 106, 1, 'Gyula az év folyamán több alkalommal is különböző fesztiválokkal várja a városlakókat és a városba érkező turistákat. A Gyulai vár, a várfürdő, a pálinka és a kolbász hazája számos kulturális, zenés és gasztro rendezvénnyel, múzeumokkal, koncertekkel, szí'),
(600, 'Nemzetközi Betlehemes Találkozó Debrecen 2024', '2024. december 7. (szombat) ', 62, 1, 'Idén ismét megrendezésre kerül 2024. december 7-én a Debreceni Betlehemes Találkozó! Sok szeretettel várunk minden érdeklődőt programunkra. A találkozó központi helyszíne a DEMKI Ifjúsági Hát. 14 csoport több 100 betlehemese határon innen és túlról érkezi'),
(601, 'Erdélyi fesztiválok 2024 / 2025. Fesztiválok, rendezvények, események', '2024. december 7. (szombat) ', 62, 1, 'Erdélyi fesztiválok programajánló. Gasztronómiai, kulturális, művészeti, hagyományőrző, színházi fesztiválok sokasága vár ránk Erdélyben.'),
(602, 'Gasztrotörténelem előadások 2024', '2024. december 7. (szombat) ', 62, 1, 'Gasztrotörténeti előadások.'),
(603, 'Csak a Mentes Karácsonyi Vásár 2024 Budapest', '2024. december 7. (szombat) - 2024. december 8. (vasárnap) ', 48, 1, 'Csak a Mentes Karácsonyi Fesztivál - Minden mentes egy helyen. Magyarország egyik legnagyobb mentes és egészségmegőrző rendezvénye Budapesten. Készüljünk együtt a mentes karácsonyra és zárjuk az idei rendezvényszezont. Bejgli, szaloncukor, ajándékok, mind'),
(604, 'Csak a Mentes Fesztivál 2024 Budapest. Őszi Fesztivál', '2024. december 7. (szombat) - 2024. december 8. (vasárnap) ', 48, 1, '\r\nAz új otthonunk pedig nem más, mint a Mom Sport. Főszerepben a természetes szépségápolás, így szakemberek, workshopok és előadások váltják egymást a témában.'),
(605, 'Cziffra György Fesztivál 2024 / 2025', '2024. december 9. (hétfő) ', 48, 1, 'A Cziffra György Fesztivál 2024 / 2025-ben is változatos programokkal várja az érdeklődőket. Tizedik alkalommal rendezik meg a Cziffra György Fesztivált Budapest több helyszínén. A Balázs János Kossuth-díjas zongoraművész által alapított hiánypótló rendez'),
(606, 'Barokk Fesztivál Érd 2024', '2024. december 13. (péntek) ', 84, 1, '2024 őszén Barokk zenei fesztivállal várja Érden a klasszikus zene iránt érdeklődőket. Októbertől decemberig az Érdi Kamarazenekar előadásában három lenyűgöző hangversennyel, és szakértők tolmácsolásában három izgalmas, a barokk kor hangszereiről szóló el'),
(607, 'Palacsintafesztivál 2024 Balatonalmádi. Palacsinta, Kolbász és Mikulásfesztivál Almádiban', '2024. december 6. (péntek) - 2024. december 12. (csütörtök) ', 18, 1, 'Várunk mindenkit szeretettel a Balaton legszebb karácsonyi vásárába, ahol Palacsinta, Kolbász és Mikulásfesztivál várja a látogatókat 2024. december 6 és 12 között. Hatalmas jégpálya is üzemel, ami a vásár alatt nyitva tart. A belépés ingyenes és kutyabar'),
(608, 'Advent Balatonlelle 2024 / 2025', '2024.11.30. (szombat) - 2025.01.31. (péntek) ', 24, 1, 'Jégfesztivál Balatonlellén  2024. november 30 és 2025. január 31. között. A  fesztivál helyszíne a Balatonlellei Napfény strand területén, valamint a vele határos Rózsapark területén kialakított rendezvényhelyszínen lesz. Jégpálya, fűtött sátor is helyet '),
(609, 'Magyar Filmszemle 2025', '2025. február 3. (hétfő) - 2025. február 9. (vasárnap) ', 48, 1, '2025. február 3-9. között a budapesti Corvin Mozi lesz a színhelye a megújuló 44. Magyar Filmszemlének, ahol 13 év szünet után találkozhatunk.'),
(610, 'Országos Táncművészeti Fesztivál 2025', '2025.02.08. (szombat) - 2025.05.17. (szombat) ', 48, 1, 'XXXIV. Országos Táncművészeti Fesztivál rendezvénysorozat 2025. évi eseményei.'),
(611, 'Áprilisi fesztiválok 2025', '2025. április 1. (kedd) - 2025. április 30. (szerda) ', 48, 1, 'Tavaszi művészeti, gasztronómiai, hagyományőrző fesztiválok. Programajánló.'),
(612, 'OFF-Biennále 2025 Budapest', '2025.05.01. (csütörtök) - 2025.06.15. (vasárnap) ', 48, 1, '2025-ben lesz az OFF-Biennále ötödik kiadása! Nagy örömmel jelentjük be, hogy 2025. május 1. és június 15. között újra megrendezzük az OFF-Biennálét! Az ötödik kiadás egyben az OFF tizedik születésnapjának ünnepe is lesz: épp egy évtizede, 2015 tavaszán i'),
(613, 'Magyar Vár Tábor és Népművészeti Fesztivál 2025 Pomáz', '2025. július 7. (hétfő) - 2025. július 13. (vasárnap) ', 243, 1, 'Jövőre újra Magyar Vár Tábor és Népművészeti Fesztivál 2025. július 7 és 23. között Pomázon! Tánccsoportok jelentkezését már most fogadjuk!'),
(614, 'Cziffra György Fesztivál 2024 / 2025', '2024. december 9. (hétfő) ', 243, 1, 'A Cziffra György Fesztivál 2024 / 2025-ben is változatos programokkal várja az érdeklődőket. Tizedik alkalommal rendezik meg a Cziffra György Fesztivált Budapest több helyszínén. A Balázs János Kossuth-díjas zongoraművész által alapított hiánypótló rendez'),
(615, 'Hanukafeszt 2024', '2024. december 28. (szombat) - 2024. december 29. (vasárnap) ', 48, 1, 'Hanukafeszt 2024. Ünnepeljünk együtt, gyújtsuk meg a hanukai gyertyákat, melegedjünk a jóság, tisztaság és remény lángjainál közösen! A nyolc napos Hanuka a zsidóknak a szíriai görög hódítók felett i. e. 165-ben aratott győzelmére, a jeruzsálemi szentély '),
(616, 'Régizene Fesztivál 2025. Online jegyvásárlás', '2025. február 21. (péntek) ', 48, 1, 'Világhírű szólisták és a legismertebb együttesek szerepelnek a Régizene Fesztiválon. Online jegyvásárlás.'),
(617, 'Bartók Tavasz 2025. Nemzetközi Művészeti Hetek', '2025. április 4. (péntek) - 2025. április 13. (vasárnap) ', 48, 1, 'A Bartók Tavasz Nemzetközi Művészeti Hetek 2025. Április 4. és 13. között ismét kihagyhatatlan programokkal várja a nézőket Budapest-szerte a Bartók Tavasz: közös koncertet ad Diana Damrau és Jonas Kaufmann, miközben Kelemen Barnabás a Münchner Philharmon'),
(618, 'Budapest Ritmo Fesztivál 2025', '2025. április 10. (csütörtök) - 2025. április 12. (szombat) ', 48, 1, 'Utazás a világ körül a 10. Budapest Ritmóval! A Budapest Ritmo, Közép-Európa egyik legjelentősebb világzenei fesztiválja.  A korábbi fesztiválokon 66 országot jártunk be 168 zenekarral. Sivatagi rock, afro-francia chansonok vagy éppen ciprusi pszichedélia'),
(619, 'Jazztavasz 2025. Online jegyvásárlás', '2025. május 9. (péntek) - 2025. május 11. (vasárnap) ', 48, 1, 'A Jazztavasz zenei fesztivál a Művészetek Palotájában 2025-ben. Online jegyvásárlás!'),
(620, 'Budapesti Wagner Napok 2025. Online jegyvásárlás', '2025. június 6. (péntek) ', 48, 1, 'Méltán népszerű Budapesti Wagner-napok a Müpában 2025-ben. Online jegyvásárlás. A mára kultikussá vált eseménysorozat évről évre Budapestre csábítja a Wagner-rajongókat a világ minden tájáról.'),
(621, 'Óperencián túl - Mese Zene Fesztivál 2025 Budapest. Kulturális és szórakoztató fesztivál gyerekeknek', '2025. június 7. (szombat) ', 48, 1, 'Mese zene fesztivál 2025. Online jegyvásárlás! Érkezik Magyarország első kulturális és szórakoztató gyerekfesztiválja Feke Pál rendezésében. Ajándékozzon élményt idén karácsonykor az egész családnak!'),
(622, 'VeszprémFest 2025 Veszprém', '2025. július 8. (kedd) - 2025. július 12. (szombat) ', 335, 1, '5 nap, 5 világsztár - VeszprémFest 2025. július 8–12. A VeszprémFest egy immár 15 éves múltra visszatekintő kulturális nagyrendezvény, amely igazi értéket teremt helyi és országos viszonylatban is az igényes zene- és művészetkedvelők örömére.'),
(623, 'Dabasi vásár 2024. Állat- és kirakodóvásár minden hónapban Dabason', '2024. december 8. (vasárnap) ', 61, 2, '2024-ben is minden hónap 2. vasárnapján felbolydul az élet Dabason! Ekkor kerül megrendezésre az Országos állat- és kirakodóvásár, ahol árusok sokasága települ ki már hajnaltól a dabasi vásártérre. Igazi piaci hangulattal,  ruhák, bútorok, régiségek, aján'),
(624, 'Egri Advent 2024. Ünnepi programok, események, rendezvények', '2024.11.29. (péntek) - 2024.12.24. (kedd) ', 78, 2, 'Magyarország egyik legszebb és legvarázslatosabb karácsonyi vásárát 2024. november 29. és december 24. között rendezik meg Egerben. A történelmi belváros meghittsége és a fényárban úszó Dobó tér, háttérben a csodálatos Egri várral, évről-évre sokakat leny'),
(625, 'Karácsonyi vásár Eger 2024', '2024.11.29. (péntek) - 2024.12.24. (kedd) ', 78, 2, 'Magyarország egyik legszebb és legvarázslatosabb karácsonyi vásárát 2024. november 29. és december 24. között rendezik meg Egerben. Váljon Eger a Te igazi történeteddé, zárd szívedbe az élményt! Eger Advent - több, mint egy ünnep! Töltődj fel, Budapesttől'),
(626, 'Kézműves kirakodóvásár Halászi 2024. Mikulás és Karácsonyváró kézműves és kirakodóvásár', '2024. december 6. (péntek) ', 78, 2, 'Gyere és fedezd fel a helyi kézművesek egyedi alkotásait Halásziban! 2024. december 6-án és 14-én délután tartjuk az idei év utolsó vásárait, oda is várunk mindenkit szeretettel és szívvel készült termékekkel.'),
(627, 'Nagy Budapesti Kultúrzsibi 2024. Gozsdu Weekend Market', '2024. december 6. (péntek) - 2024. december 9. (hétfő) ', 48, 2, 'Nagy Budapesti Kultúrzsibi 2024. Gozsdu Weekend Market - Kézműves, design, art, vintage, ékszer- és dísztárgyvásár a Gozsdu Udvarban! A Gozsdu Weekend Market egy streetmarket (utcai vásár) amely fergeteges piaci hangulattal, változatos portékákkal,antik é'),
(628, 'Mórahalom Országos Kirakodó és Állatvásár 2024', '2024. december 15. (vasárnap) ', 199, 2, 'Országos Kirakodó és Állatvásár Mórahalmon! 2024-ben is minden hónap 3. vasárnapja a vásárról szól Mórahalmon, ahol árusok és eladók sokasága érkezik a mórahalmi vásártérre. Színes áruválasztékkal, igazi vásári forgataggal várják a látogatókat,a piacon ru'),
(629, 'TerraPlaza 2024 Budapest. Nemzetközi egzotikus állat kiállítás, vásár és szakmai nap', '2024. december 15. (vasárnap) ', 48, 2, 'TerraPlaza 2024, Budapest - Egzotikus állat kiállítás és vásár, mely nem csak Közép-Európa egyik legnagyobb terrarisztikai és akvarisztikai rendezvénye, hanem közönségtalálkozó és egy életforma is egyben. Száz válogatott nemzetközi kiállító és több ezer l'),
(630, 'Debreceni Régiségvásár 2024. Idén 25 éve rendezik meg Debrecenben a méltán népszerű régiségvásárt!', '2024. december 15. (vasárnap) ', 62, 2, 'Idén 25 éves a Debreceni Régiségvásár! Márciustól minden hónap második és negyedik vasárnapján, reggel 7-től a Nagyerdei Stadionnál, a  régiségek, műtárgyak körébe tartozó tárgyak, eszközök, pénzérmék, medálok, fegyverek, bútorok mellett antikváriusok is '),
(631, 'Buffalo Market Kézműves Régiségvásár és Zsibvásár 2024 Szerencs', '2024. december 14. (szombat) ', 286, 2, 'Hagyományteremtő vásárok és gourmet ízek, Szerencsen! 2024 márciusától, minden hónap 3. szombatján, Buffalo Market kézműves-, régiségvásár és zsibvásár Szerencsen, a Buffalo Bill western étterem melletti piactéren. A vásár 8.00-tól 14.00-ig látogatható, a'),
(632, 'Pólus Karácsony 2024 Budapest. Varázslatos hely mesebeli dekorációkkal és változatos programokkal', '2024. december 6. (péntek) - 2024. december 22. (vasárnap) ', 48, 2, 'Hangolódjunk az ünnepre: karácsonyi csodaország vár ránk a Pólusban! Látványos, varázslatos dekorációk, óriáscukorkák, mesebeli diótörő-figurák gondoskodnak arról, hogy ez a csodaország egy olyan lenyűgöző hely legyen, amely felejthetetlen élményt nyújt a'),
(633, 'Palacsintafesztivál 2024 Balatonalmádi. Palacsinta, Kolbász és Mikulásfesztivál Almádiban', '2024. december 6. (péntek) - 2024. december 12. (csütörtök) ', 18, 2, 'Várunk mindenkit szeretettel a Balaton legszebb karácsonyi vásárába, ahol Palacsinta, Kolbász és Mikulásfesztivál várja a látogatókat 2024. december 6 és 12 között. Hatalmas jégpálya is üzemel, ami a vásár alatt nyitva tart. A belépés ingyenes és kutyabar'),
(634, 'Advent Hatvan 2024. Ünnepi programok, események, rendezvények', '2024.11.30. (szombat) - 2024.12.22. (vasárnap) ', 116, 2, 'Ünnepi programok Hatvanban. 2024. november 30-án Hatvanban is kezdetét veszi az adventi időszak, városunk ünnepi díszbe öltözik.'),
(635, 'Nemesvámosi Vásár 2024. Adventi vásár', '2024.11.29. (péntek) - 2024.12.22. (vasárnap) ', 116, 2, 'Az idei évben Nemesvámos egy nagyszabású Adventi Vásárt szervez 2024. november 19 és december 22. között, amelyen az ünnepi ráhangolódás és a közösségek összefogása lesz a központban.'),
(636, 'Karácsonyi vásár Miskolc 2024. Adventi varázslat a Szent István téren', '2024.11.29. (péntek) - 2024.12.23. (hétfő) ', 195, 2, 'Karácsonyi Vásár Miskolc belvárosában, a Szent István téren 2024. november 29 - december 23. között.  Ünnepi hangulat, gyertyagyújtás, kézműves foglalkozások, gyermekeknek szóló programok, szabadtéri koncertek és sok finomság várja az érdeklődőket.'),
(637, 'Advent Makó 2024. Makói Adventi Vásár', '2024.11.30. (szombat) - 2024.12.22. (vasárnap) ', 178, 2, 'Makó Városa 2024. november 30 és december 22. között színesebbnél színesebb programokkal kedveskedik az adventi hétvégéken. Az elsőtől az utolsóig kulturális és szórakoztató programok lepik el a Makovecz teret, ezek után pedig a környéken sétálva az ünnep'),
(638, 'Adventi Kézműves Vásár 2024 Békéscsaba', '2024.11.30. (szombat) - 2024.12.24. (kedd) ', 32, 2, 'Idén új attrakció, kézműves karácsonyi vásár is lesz a csabai piacon, kézműves portékákat kínálnak majd a csabai piac karácsonyi vásárán. Aki idén karácsonyi hangulatra, programkavalkádra vágyik, az a Szent István térre menjen, aki pedig egyedi ajándékoka'),
(639, 'Aukciók 2024', '2024. december 1. (vasárnap) - 2024. december 19. (csütörtök) ', 32, 2, 'Könyvek, régiségek, művészeti alkotások, műtárgyak árverési naptára.'),
(640, 'Advent Csabrendek 2024', '2024. december 1. (vasárnap) - 2024. december 24. (kedd) ', 32, 2, 'Adventi programok Csabrendeken.'),
(641, 'Advent Dunavecse 2024', '2024. december 1. (vasárnap) - 2024. december 24. (kedd) ', 76, 2, 'Adventi programok Dunavecsén.'),
(642, 'Advent Bátonyterenye 2024', '2024. december 4. (szerda) - 2024. december 24. (kedd) ', 29, 2, 'Adventi programok Bátonyterenyén. Készülődjünk az ünnepekre közösen!'),
(643, 'Siófoki adventi programok 2024. Téli Varázs Siófokon', '2024.11.30. (szombat) - 2024.12.24. (kedd) ', 267, 3, 'Adventi programkavalkád  Siófok városában, hisz Siófok télen is varázslatos! Az idei évben is egy mesebeli Adventi időszakkal vár Siófok! Siófok és a Balaton téli varázsa idén is mindenkinek jár! Siófok idén decemberben is mindenki lelkét az ünnepekre han'),
(644, 'Gárdonyi Levendula workshop programok 2024. Alkossunk együtt adventi - karácsonyi ünnepi hangulatban', '2024. december 7. (szombat) ', 95, 3, 'Csatlakozz hozzánk különleges, kreatív workshop sorozatunkra! Minden, amit a workshopon használunk, természetes és környezetbarát alapanyagokkal és kellemes levendulaillatú környezetben. Neked semmit sem kell magaddal hoznod – minden alapanyagot és eszköz'),
(645, '2024. december 24. Budapest, karácsonyi hajós program Szenteste ínyencségekkel és élőzenével', '2024. december 24. (kedd)  19:00', 48, 3, 'Ha szeretné egy különleges, és meghitt karácsonyi hangulatban tölteni a téli ünnepeket akkor a karácsonyi varázzsal átitatott Gróf Széchenyi hajón a helye. Töltsük együtt ezt a meghitt és békés adventi időszakot!'),
(646, 'Karácsonyi program Budapesten, karácsonyi vacsora sétahajózással és élőzenével', '2024. december 24. (kedd)  19:00', 48, 3, 'Ha szeretné egy különleges, és meghitt karácsonyi hangulatban tölteni a téli ünnepeket akkor a karácsonyi varázzsal átitatott Gróf Széchenyi hajón a helye. Töltsük együtt ezt a meghitt és békés adventi időszakot!'),
(647, 'Karácsonyi program Budapesten, ünnepi sétahajózás gyertyafényes vacsorával és élőzenével', '2024. december 24. (kedd)  19:00', 48, 3, 'Ünnepi hangulatú hajókázással várjuk vendégeinket karácsonykor, 19:00 órától. A különleges karácsonyi hajós programot azon vendégeknek hoztuk létre, akik szeretnének meghitt karácsonyi hangulatban ünnepelni a Dunán. Vendégeink megcsodálhatják a fényben ús'),
(648, 'Nagytemplomi Adventi Koncertek Debrecen 2024', '2024. december 9. (hétfő) ', 62, 3, '2024. évi Nagytemplomi Adventi Koncertek Debrecenben. Ebben az évben négy koncert kerül megrendezésre. Híres és méltán népszerű művészek lépnek fel a remek akusztikájú Debreceni Református Nagytemplomban. Koncertet ad Soltész Rezső, Szekeres Tamás az Omeg'),
(649, 'Zenekarácsony Békéscsaba 2024. Ünnepi szuperkoncertek sztárokkal kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 32, 3, 'Zenekarácsony, ünnepi koncertek Békéscsabán, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a'),
(650, 'Zenekarácsony Debrecen 2024. Karácsonyi sztárözön, ünnepi szuperkoncertek kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 62, 3, 'Zenekarácsony, ünnepi koncertek Debrecenben, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a'),
(651, 'Zenekarácsony Szeged 2024. Ünnepi szuperkoncertek kicsiknek és nagyoknak karácsonyi hangulatban', '2024. december 26. (csütörtök) ', 277, 3, 'Zenekarácsony, ünnepi koncertek Szegeden, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a hé'),
(652, 'Zenekarácsony Szombathely 2024. Ünnepi koncertek sztárokkal kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 293, 3, 'Zenekarácsony, ünnepi koncertek Szombathelyen, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit'),
(653, 'Szilveszter Egerben 2024. Programok, események, rendezvények', '2024. december 31. (kedd) ', 78, 3, 'Töltse a szilvesztert Egerben! Programajánló.'),
(654, 'Adventi hétvégék Dobogókőn, wellnesszel és ünnepi programokkal a Cardoner Hotelben', '2024. december 6. (péntek) - 2024. december 8. (vasárnap) ', 78, 3, 'A karácsonyi hangolódás egy várakozásteli időszak, melyet az adventi hétvégék tesznek varázslatossá. Dobogókőn megpihenhetsz, kizárva a külvilágot, és megtervezheted, hogyan szeretnéd ünnepelni a karácsonyt. Töltődj fel a természettel, az illatokkal és pi'),
(655, 'Szilveszter Dobogókőn gálavacsorával és wellnesszel a Cardoner Hotelben', '2024.12.29. (vasárnap) - 2025.01.01. (szerda) ', 78, 3, 'Élményekkel teli szilveszter a Cardoner Hotelben! Köszöntsük együtt a 2025-es esztendőt a csodálatos Dobogókőn, ahol élményprogramokkal és élőzenével, gálavacsorával, korlátlan italcsomaggal és egész estés szórakozással várjuk vendégeinket! A gálavacsora '),
(656, 'Mikulás rendelés 2024. Házhoz jön a Mikulás, és valóra váltja a gyermekek álmát', '2024. december 1. (vasárnap) - 2024. december 23. (hétfő) ', 48, 3, 'A Mikulás eljön, ha hívják! Mikulás szolgáltatásunk 2024. december 23-ig elérhető Budapesten és vonzáskörzetében. A családoknál és a cégeknél, valóra váltjuk a mesét, de az üzletekben is vevő csalogató lehet a megrendelt Mikulás.'),
(657, 'Luxus karácsony Siófokon, ünnepi finomságokkal a Reed Luxury Hotelben', '2024. december 24. (kedd) - 2024. december 26. (csütörtök) ', 267, 3, 'Luxus karácsony megannyi gasztro élménnyel különleges környezeteben a siófoki Reed Hotelben. Karácsonykor nálunk megtalálja az igazi ünnepi békét és kényelmet, ahol minden részlet a tökéletességre törekszik. Hagyja magát elvarázsolni nálunk, és fedezze fe'),
(658, 'Két ünnep közötti pihenés Siófokon, gasztro és wellness élményekkel a Reed Luxury Hotelben', '2024. december 27. (péntek) - 2024. december 30. (hétfő) ', 267, 3, 'Két ünnep közötti luxus pihenés Siófokon, a nyugalom szigetén, a Reed Luxury Hotelben. Ebben az egyedülálló időszakban, kissé megpihenve az ünnepek között szállodánk varázslatos díszekkel és meleg hangulattal várja Önöket, miközben egyedi szolgáltatásaink'),
(659, 'Karácsonyi vásár 2024 Budapest. Minden ajándék egy helyen, a World Mall bevásárlóközpontban!', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 3, 'Az advent időszakában is várja a látogatókat a World Mall, ahova már megérkezett a karácsonyi varázslat – és biztos, hogy nem lesz hiány sem ajándékból, sem dekorációból! Ha elkerülnéd a bevásárlási hajszát és inkább kényelmesen, egy csésze forró csokolád'),
(660, 'Karácsony előtti wellness pihenés kedvezményes áron a Tisza Balneum Hotelben', '2024. december 1. (vasárnap) - 2024. december 20. (péntek) ', 305, 3, 'Pihenjen rá a karácsonyi pörgésre a tiszafüredi Balneum Hotelben. Svédasztalos félpanziós ellátással, korlátlan wellness használattal, masszázs- és wellness kezelésekkel, szaunarituálékkal várjuk vendégeinket.'),
(661, 'Karácsonyi céges vacsora Tiszafüreden a Balneum Hotelben', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 305, 3, 'Karácsonyi céges vacsora Tiszafüreden a Balneum Hotelben. Szeretnédmegköszönni kollégáinak egész éves munkájukat? Mi garantáljuk, hogy az évzáró vacsorára a legjobb helyszín a Tisza Balneum Hotel****! Használják ki az év utolsó perceit és értékeljék ki ná'),
(662, 'Karácsonyi wellness kikapcsolódás a Tisza-tónál,  ünnepi programokkal a Balneum Hotelben', '2024. december 20. (péntek) - 2024. december 29. (vasárnap) ', 305, 3, 'Meghitt Karácsony a jégvirágos Tisza-tó partján. Töltse ünnepi hangulatban, mesebeli hóesésben a szeretet ünnepét Tiszafüreden a Balneum Hotelben! Fenséges zenés-táncos karácsonyi vacsorával, gesztenyesütögetéssel a hókristályos Tisza-parton és animációs '),
(663, 'Télapó programok 2024', '2024. december 1. (vasárnap) - 2024. december 8. (vasárnap) ', 305, 3, 'Számos Télapó rendezvény, program, esemény várja a gyerekeket és felnőtteket az ország különböző pontján, decemberben. Mikulás, kézműves foglalkozások, gyermek előadások, bábelőadások, ünnepi zenés-játékos rendezvények, gyermekkoncertek várják a kicsiket-'),
(664, 'Karácsonyi koncert Orosháza 2024. Gájer Bálint Swing karácsonyi lemezbemutató koncert', '2024. december 6. (péntek) ', 222, 3, 'Gájer Bálint Swing karácsonyi lemezbemutató koncertje 2024. december 6-án lesz Orosházán a Petőfi Művelődési Központban. A legnépszerűbb karácsonyi világslágerek kerülnek fel Gájer Bálint 5. nagylemezére magyar nyelvű szövegekkel.'),
(665, 'Advent Vajdahunyad Vár 2024. Adventi koncertek, online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Advent Vajdahunyad Vár 2024. A Vajdahunyad vára az épülő, szépülő Liget ikonikus épülete, a téli időjárás pedig csodás mesekastéllyá változtatja a környékét. A nemrég megújult Vajdahunyadvár Jáki kápolnájában, a neoromán falak között ádventi dallamok csen'),
(666, 'Budafoki Advent 2024. Online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Adventi programajánló 2024. Programok a Budafok-Tétényi Klauzál Gábor Művelődési Központban az adventi időszakban.'),
(667, 'Fővárosi Nagycirkusz karácsonyi műsora 2024. Online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Fővárosi Nagycirkusz karácsonyi műsora 2024. Online jegyvásárlás! Kápráztató csodákkal vár a Fővárosi Nagycirkusz új műsora!'),
(668, 'Jegyek Karácsonyra 2024. Karácsonyi programok és online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Jegyek programokra, koncertekre a karácsonyi időszakban 2024-ben. Adventkor és a karácsonyt megelőző hetekben is számos ünnepi rendezvény, előadás, színház, családi és gyermekprogram várja a közönséget. Hazai együttesek, zenekarok és előadóművészek az ünn'),
(669, 'Klauzál Ház Advent 2024', '2024. december 6. (péntek) ', 48, 3, 'Advent a Klauzál Házban és társintézményeiben 2024-ben.'),
(670, 'Mikulás koncertek 2024. Online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Koncertek kicsiknek és nagyoknak Mikulás ünnepe alkalmából 2024-ben. Online jegyvásárlási lehetőség.'),
(671, 'Mikulás programok 2024. Online jegyvásárlás', '2024. december 6. (péntek) ', 48, 3, 'Számos Mikulás program, rendezvény, esemény várja a gyerekeket és felnőtteket az ország különböző pontján 2024-ben.'),
(672, 'Mikulás Ócsa 2024', '2024. december 6. (péntek) ', 220, 3, 'Találkozz a Mikulással Ócsán, az Egressy Gábor Szabadidőközpontban 2024. december 6-án! 18.00 órától vendégünk Masni és Pocó Mihályi Rékával. A bábokkal színesített interaktív koncertre várjuk a gyermekeket. A koncert után a gyerkőcök találkozhatnak a Mik'),
(673, 'Budapesti esti hajózás élőzenével, vacsorával 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 7. (szombat)  19:00', 48, 4, '2 órás hajókázásunk egy köszöntő itallal kezdődik, melyet légkondicionált hajóinkon szolgálunk fel Önnek. A hajón a zenét a Kodály Zoltán díjas Hungária Zenekarból 3 zenész szolgáltatja.'),
(674, 'Budapesti éjszakai program, hajókirándulás élőzenével, vacsorával 22:00 órakor', '2024. december 24. (kedd)  22:00', 48, 4, 'Egyedi romantikus és felejthetetlen élményt kínálunk Önnek Budapesten! Éjszakai panoráma hajókirándulást vacsorával vagy vacsora nélkül, miközben megcsodálhatja a kulturális világörökségnek nyilvánított budapesti panorámát. A este 10 órakor induló látvány'),
(675, 'Éjszakai hajós városnézés Budapesten - JEGYVÁSÁRLÁS', '2024. december 24. (kedd)  22:00', 48, 4, 'Éjszakai hajós városnézés Budapesten májustól október végéig minden pénteken és szombaton 22:00 órától, májustól szeptember végéig csütörtök este is.'),
(676, 'Siófoki adventi programok 2024. Téli Varázs Siófokon', '2024.11.30. (szombat) - 2024.12.24. (kedd) ', 267, 4, 'Adventi programkavalkád  Siófok városában, hisz Siófok télen is varázslatos! Az idei évben is egy mesebeli Adventi időszakkal vár Siófok! Siófok és a Balaton téli varázsa idén is mindenkinek jár! Siófok idén decemberben is mindenki lelkét az ünnepekre han'),
(677, 'Kecskeméti programok 2024 / 2025. Fesztiválok, rendezvények, események, jeles napok, ünnepek', '2024.11.29. (péntek) - 2024.12.13. (péntek) ', 141, 4, 'Kecskemét 2024. évi programajánló naptára. Fesztiválok, kiállítások, művészeti és kulturális események, gasztronómiai programok, vásárok, konferenciák, vendégváró események egész évben a hírös városban minden korosztálynak. Színes programkínálattal, szính'),
(678, 'Keszthelyi programok 2024 / 2025. Fesztiválok, események, rendezvények, jeles napok, ünnepek', '2024. december 2. (hétfő) - 2024. december 6. (péntek) ', 146, 4, 'Keszthelyi programajánló érdekes és értékes programokkal. Színes a kulturális programkínálat egész évben. A Festetics-kastély, a történelmi belváros, szervezett városi séták, fesztiválok, kiállítások, koncertek, színházi előadások, filmvetítések, múzeumi '),
(679, 'Siófoki programok 2024 / 2025. Fesztiválok, események, rendezvények', '2024.11.30. (szombat) - 2024.12.31. (kedd) ', 267, 4, 'Városnapi forgatag, adventi programkavalkád, panorámás jégpálya és hófánkpálya, óriáskerék - Siófok télen is varázslatos! A  Balaton fővárosában töltött téli pihenés garantáltan élményekkel és varázslatos pillanatokkal teli lesz 2024-ben is. Legyen szó kö'),
(680, 'Balatonfüredi eseménynaptár 2024 / 2025. Programok, rendezvények, fesztiválok', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 21, 4, 'Balatonfüredi 2024. évi programajánló. Balatonfüred egész évben változatos programokkal fogadja az ide érkezőket. A népszerű kisváros a Balaton északi partján rendkívül gazdag kulturális, bor-és gasztronómiai fesztiválokban, látnivalókban, Balatonfüred a '),
(681, 'Zalakarosi programok 2024. Események, rendezvények, fesztiválok', '2024. december 6. (péntek) - 2024. december 8. (vasárnap) ', 341, 4, 'Zalakarosi programajánló érdekes és értékes 2024. évi programokkal. A fürdővárosban színes a kulturális, a gasztronómiai- és a fürdőprogram kínálat egész évben. Kiállítások, koncertek, színházi előadások, filmvetítések, fesztiválok, gyógy- és élményfürdő,'),
(682, 'Koktélhajó Budapesten 19:00 órától, városnézés koktélokkal a Dunán  -JEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 4, 'Gyönyörködjön Budapest nevezetességeiben, miközben egy pohár hideg koktélt szürcsölget hangulatos városnéző hajónk nyitott erkélyén! Hajónkon zárt, belső fedélzet is található, ahol panoráma ablakok mögül szemlélheti a várost. A program 2 alkoholtartalmú,'),
(683, 'Budapest esti hajó, városnézés a Dunán élőzenével 19:00 órától - jEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 4, 'A hajó a város 6 legfőbb hídja alatt halad át, miközben a nap lassan lenyugszik a budai hegyek mögött átfestve Budapest látványosságait. Gyönyörködj a Parlament, a Budai vár, a Nemzeti Színház, a Művészetek Palotája és a város sok más lélegzetelállító épü'),
(684, 'Budapesti városnézés hajóval minden nap 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 4, 'Városnéző hajóprogram Budapesten.  2 órás hajókázásra várjuk nyáron légkondicionált, télen fűtött hajóinkon.'),
(685, 'Budapesti randevú a Dunán, sétahajózás itallal vagy vacsorával 19:00 órától- JEGYVÁSÁRLÁS', '2024. december 7. (szombat)  19:00', 48, 4, '2 órás hajókázásunk egy köszöntő itallal kezdődik, melyet légkondicionált hajóinkon szolgálunk fel Önnek. A hajón a zenét a Kodály Zoltán díjas Hungária Zenekarból 3 zenész szolgáltatja. Programunk vacsora nélkül is meglátogatható.'),
(686, 'Budapesti sétahajózás vacsorával 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 7. (szombat)  19:00', 48, 4, 'Budapesti sétahajózás vacsorával programunk azon vendégeink számára készült, akik  szívesen fogyasztanák el vacsorájukat romantikus hangulatban. Találkozás a program kezdete előtt 30 perccel.'),
(687, 'Sétahajózás a Dunán Budapesten, minden nap 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 7. (szombat)  19:00', 48, 4, 'Sétahajózás a Dunán Budapesten ínyencségekkel és élő zenével fűszerezve programunk azon vendégeink számára készült, akik szeretik az élőzenét, és szívesen fogyasztanák el vacsorájukat romantikus hangulatban. 2 órás hajókázásunk egy köszöntő itallal kezdőd'),
(688, 'Zenés vacsora romantikus hajós városnézéssel Budapesten 19:00 órától- JEGYVÁSÁRLÁS', '2024. december 7. (szombat)  19:00', 48, 4, 'Hozza el kedvesét egy romantikus vacsorára és tegye egy hajókázással emlékezetessé! Köszöntőitallal, gyertyafénnyel, ínycsiklandó büfévacsorával és további italokkal várjuk! A romantikus hangulatról az élőzene és Budapest esti fényei gondoskodnak.'),
(689, 'Borhajó Budapesten, élőzenés sétahajózás borkóstolóval, ínyencségekkel 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 4, 'Lépjen fedélzetünkre és ismerje meg a várost a lehető legszebb perspektívából. A Duna vizéről Budapest leggyönyörűbb látványosságai tárulnak a szeme elé, mint a Parlament, a Bazilika vagy a Nagy Vásárcsarnok. A folyó túloldalán feltekinthet a lélegzetelál'),
(690, 'Borsos Miklós Emléklakás programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 4, 'A Borsos Emléklakásban a régi bútorok és használati tárgyak – mint például a művész Firenzében vásárolt reneszánsz székei, gyönyörű erdélyi utazóládája, kézi csomózású perzsa szőnyege, eredeti csillárja és könyvei – mellett állandó kiállítást alakítottak '),
(691, 'Virág Benedek Ház programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 4, 'Igényes szórakozás, minőségi időtöltés, minden generáció érdeklődését felölelő kulturális programpaletta, értékes kapcsolatok és barátságos fogadtatás Budán. A Virág Benedek Ház gyönyörű tabáni épület, kiállítótér és kulturális-közösségi központ. Felejthe'),
(692, 'Vonyarcvashegyi programok 2024. Fesztiválok, események, rendezvények', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 48, 4, 'Vonyarcvashegyi programajánló érdekes és értékes programokkal. Színes a kulturális és gasztronómiai programkínálat egész évben. A Balaton északi partján fekvő Vonyarcvashegyen koncertek, színházi előadások, fesztiválok, strand és még számos szabadidős gar'),
(693, 'Szombathelyi programok 2024 / 2025. Fesztiválok, rendezvények, események', '2024.11.22. (péntek) - 2024.12.23. (hétfő) ', 293, 4, 'Szombathely minden évszakban színes kulturális programokat kínál. Az Érezd Szombathelyt! elnevezésű  programkavalkád szinte minden hétvégén változatos, izgalmas, könnyed, szórakoztató zenei-, gasztro-, művészeti-, sőt sporteseményekkel vár minden kikapcso'),
(694, 'Miskolci programok 2024 / 2025. Fesztiválok, események, rendezvények', '2024.11.28. (csütörtök) - 2024.12.08. (vasárnap) ', 195, 4, 'Miskolci programajánló érdekes és értékes programokkal. Színes a kulturális programkínálat egész évben. Miskolcon kiállítások, koncertek, fesztiválok, színházi előadások, filmvetítések, barlangfürdő, gasztronómiai és zenés programok, szabadtéri színpadi e'),
(695, 'Salgótarjáni programok 2024 / 2025. Fesztiválok, rendezvények, események', '2024.11.29. (péntek) - 2024.12.21. (szombat) ', 256, 4, 'Változatos programok, fesztiválok, rendezvények, események Salgótarjánban. Gasztronómia fesztiválok, városi ünnepségek, zenés programok, családi és gyermek előadások, színházi bemutatók, múzeumok egész évben Salgótarjánban.'),
(696, 'Debreceni programok 2024 / 2025. Fesztiválok, rendezvények, események, jeles napok, ünnepek', '2024.11.29. (péntek) - 2024.12.23. (hétfő) ', 62, 4, 'Debrecenben sosem lehet unatkozni! Debrecen turisztikailag rendkívül érdekes és vonzó város, amely gazdag kulturális örökséggel és történelmi látnivalókkal büszkélkedhet. A város számos lenyűgöző múzeummal, impozáns templomokkal és a híres Nagytemplommal '),
(697, 'Győri programok 2024 / 2025. Fesztiválok, rendezvények, események', '2024.11.29. (péntek) - 2024.12.23. (hétfő) ', 105, 4, 'Győri programajánló érdekes és értékes programokkal. Színes a kulturális programkínálat egész évben. Ebben a műemlékekben gazdag városban, kiállítások, koncertek, színházi előadások, fesztiválok, múzeumi foglalkozások, sportesemények és még számos szabadi'),
(698, 'Tokaji programok 2024 / 2025. Események, rendezvények, fesztiválok', '2024.11.30. (szombat) - 2024.12.07. (szombat) ', 310, 4, 'Fesztiválok, rendezvények, események Tokajban, a történelmi borvidék fővárosában. A település a Bodrog és a Tisza összefolyásánál található. A város fekvését megszépíti a két folyó találkozása. A hegy pedig az óváros fölé borul. Nincs még egy település ha'),
(699, 'Makói programok 2024 / 2025. Események, rendezvények, fesztiválok', '2024.11.30. (szombat) - 2024.12.22. (vasárnap) ', 178, 4, '2024. évi makói programajánló. Makó nemcsak a hagymájáról híres, de bővelkedik kulturális programokban, koncertek, kiállítások, színházi előadások, gasztronómiai programok, filmvetítések, fesztiválok várják az érdeklődő közönséget. Makón, a Hagymaház egés'),
(700, 'Dombóvári programok 2024 / 2025. Események, rendezvények, fesztiválok', '2024.11.30. (szombat) - 2024.12.31. (kedd) ', 68, 4, 'Dombóvári programajánló. Dombóvár koncertekkel, rendezvényekkel, színházzal, gyermek előadásokkal, zenés programokkal várja a közönséget. A kulturális és gasztronómiai kikapcsolódási lehetőségek mellett számos kiránduló és túraútvonal is várja a Dombóvárr'),
(701, 'Budaörsi programok 2024 / 2025. Események, rendezvények, fesztiválok', '2024. december 1. (vasárnap) - 2024. december 8. (vasárnap) ', 47, 4, 'Budaörsi programok, rendezvények 2024 / 2025. Kulturális és gasztronómiai rendezvények, fesztiválok, koncertek, színház, családi és gyermekprogramok egész évben. Szórakozás, kikapcsolódás minden korosztálynak Budaörsön, változatos, műfaji sokszínűséggel, '),
(702, 'Balatonboglár programok 2024 / 2025. Fesztiválok, rendezvények, események', '2024. december 1. (vasárnap) - 2024. december 20. (péntek) ', 19, 4, 'Balatonboglári programajánló érdekes és értékes programokkal. Színes a kulturális programkínálat egész évben. Kiállítások, koncertek, gyermekprogramok, színházi előadások, filmvetítések, sportesemények, gasztrofesztiválok és még számos szabadidős garantál'),
(703, 'Éjszakai hajós városnézés Budapesten - JEGYVÁSÁRLÁS', '2024. december 24. (kedd)  22:00', 48, 5, 'Éjszakai hajós városnézés Budapesten májustól október végéig minden pénteken és szombaton 22:00 órától, májustól szeptember végéig csütörtök este is.'),
(704, 'Budapesti orgonakoncertek híres áriákkal a Szent István Bazilikában', '2024. december 12. (csütörtök)  20:00', 48, 5, 'Budapesti orgonakoncertjeink este 20:00 órakor kezdődnek, és kb. 70 perc időtartamúak, szünet nincs. A koncert anyagát Teleki Miklós orgonaművész állította össze, aki  Magyarország legjobb orgonaművészei közé tartozik.'),
(705, 'Budapest Jazz Club programok 2024', '2024. december 6. (péntek) ', 48, 5, 'A Budapest Jazz Clubban változatos programokkal, élőzenével, magyar és világsztárokat felvonultató koncertekkel, csúcstechnikával felszerelt koncertteremben várják a minőségi zene kedvelőit. A békebeli, nosztalgikus hangulatú budapesti kávézóba és a moder'),
(706, 'Alma Együttes koncertek 2024 / 2025. Fellépések, előadások műsornaptára', '2024. december 6. (péntek) ', 48, 5, 'Az Alma Együttes mára az egyik legkedveltebb zenekar a gyermekek körében. Koncertjeiken az egyedi stílusú etno zenét játszó együttes improvizatív módon kezeli a táncos-zenés együttlétet. A gyerekek, sőt a szülők is aktív részesei és formálói a sok vidámsá'),
(707, 'MáraiKult programok 2024  Budapest. Események, rendezvények, élmény és inspiráció Buda szívében', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'A MáraiKult egyedi élményt nyújt, ahol a művelődés és a kulturális sokszínűség találkozik. Fedezze fel változatos helyszíneinket! Kulturális programkínálatunk a legszélesebb korosztály érdeklődési körének igényeit kívánja kielégíteni, az első kerületben é'),
(708, 'Tér-Kép Galéria programok 2024 Budapest', '2024. december 3. (kedd) - 2024. december 7. (szombat) ', 48, 5, 'A Tér-Kép Galéria programjai összekapcsolják a kortárs művészetet annak közönségével. A galéria letisztult, modern terében szeretjük meglepni a betérőket. A helytörténeti, a múlt hangsúlyos eseményeit, épületeit felelevenítő és megidéző tárlatok mellett f'),
(709, 'Várnegyed Galéria programok 2024 Budapest', '2024. december 5. (csütörtök) - 2024. december 7. (szombat) ', 48, 5, 'A 2004-ben alapított Várnegyed Galéria a kezdetektől fogad képzőművészeti, fotográfiai, iparművészeti tárlatokat. A grafikustól és a szobrásztól a textilművészig számos alkotó otthonra talált a Vízivárosban található kiállítótérben, amely a helyi, budai m'),
(710, 'Ismerős Arcok koncertek 2024 / 2025', '2024. december 6. (péntek) ', 48, 5, 'Az Ismerős Arcok zenekar 1999 óta van jelen a magyar könnyűzenei életben. Rendszeres szövegírói-zeneszerzői munkájával, nagyszámú közönséget vonzó koncertjeivel népszerűsíti, tudatosítja az egyetemes magyar kultúra szeretetének fontosságát. A jelenkor div'),
(711, 'Nagytemplomi Adventi Koncertek Debrecen 2024', '2024. december 9. (hétfő) ', 62, 5, '2024. évi Nagytemplomi Adventi Koncertek Debrecenben. Ebben az évben négy koncert kerül megrendezésre. Híres és méltán népszerű művészek lépnek fel a remek akusztikájú Debreceni Református Nagytemplomban. Koncertet ad Soltész Rezső, Szekeres Tamás az Omeg'),
(712, 'Csík -Presser-Karácsony: A Dal a Miénk 2.0 – Új dalokkal újratöltve', '2024. december 21. (szombat) ', 62, 5, 'Izgalmas vállalkozásba fogott a Csík Zenekar, amikor 2020-ban egy olyan lemezt adott ki, amely csak feldolgozásokat tartalmazott, ráadásul egyetlen zenekar, a Locomotív GT dalaiból válogatva! Az album megjelenését egy kétéves lemezbemutató turné követte, '),
(713, 'Borsos Miklós Emléklakás programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'A Borsos Emléklakásban a régi bútorok és használati tárgyak – mint például a művész Firenzében vásárolt reneszánsz székei, gyönyörű erdélyi utazóládája, kézi csomózású perzsa szőnyege, eredeti csillárja és könyvei – mellett állandó kiállítást alakítottak '),
(714, 'Jókai Anna Szalon programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'A Jókai Anna Szalon egy romantikus épületben helyet foglaló egyedülálló kulturális helyszín. Programkínálatában szerepelnek irodalmi és zenei előadások, kiállítások, könyvbemutatók, beszélgetések, komolyzenei koncertek, találkozások különleges emberekkel.'),
(715, 'Virág Benedek Ház programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Igényes szórakozás, minőségi időtöltés, minden generáció érdeklődését felölelő kulturális programpaletta, értékes kapcsolatok és barátságos fogadtatás Budán. A Virág Benedek Ház gyönyörű tabáni épület, kiállítótér és kulturális-közösségi központ. Felejthe'),
(716, 'Center Színház programok 2024 Budapest. Előadások kisebb és nagyobb gyerekeknek, családoknak', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Előadások gyermekeknek, családoknak, óvodás és kisiskolás gyermekcsoportoknak. Mesejátékok, bábelőadások, gyerekkoncertek. Küldetésünk, hogy a gyermekek találkozhassanak a színházkultúrával. Törekszünk rá, hogy megmutassuk nekik és megszerettessük velük e'),
(717, 'Gyula kiállítás programok 2024. Időszaki kiállítások a város kiállítóhelyein és a múzeumaiban', '2024.11.14. (csütörtök) - 2024.12.13. (péntek) ', 106, 5, 'Gyula népszerű turisztikai központ Békés megyében. A történelmi város kulturális intézményei számos kiállításnak, programnak adnak otthont egész évben. A kiállításokon többnyire a helyi és a megyén belüli művészek mutatkoznak be különböző alkotásaikkal. A'),
(718, 'Eötvös Károly Könyvtár kiállítások Veszprém 2024', '2024.12.06. (péntek) - 2025.01.05. (vasárnap) ', 335, 5, 'Időszaki kiállítások a veszprémi Eötvös Károly Könyvtárban és intézményeiben.'),
(719, 'Rececsipke kiállítás 2024 Szomolya. Megtekinthetők a szebbnél szebb terítők és tetszetős kézimunkák', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 335, 5, 'A Fekete Cseresznye Művelődési házban találhatják meg a kulturális Örökségünk részét képező rece csipke kiállításunkat. Azért is ajánlom a figyelmükbe, mert olyan különleges lehetőségben is részük lehet, hogy láthatják hogyan készülnek ezek a különleges k'),
(720, 'Falumúzeum látogatás Szomolyán, ismerje meg a jellegzetes használati eszközöket, népi mesterségeket', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 335, 5, 'A Tájház mellett van nekünk itt Szomolyán még egy, a régi korok hangulatát idéző Falumúzeumunk, ahol 300 évre visszamenőleg bemutatjuk be a jellegzetes szomolyai használati eszközöket, népi mesterségeket. Ilyenek a kőfaragó eszközök, helyi népi bútorok.'),
(721, 'Élményprogram Budapest 2024. NÉZZ BE A CSOPÁBA!', '2024. december 1. (vasárnap) - 2024. december 8. (vasárnap) ', 48, 5, 'A Csodák Palotájában attrakcióinkkal, interaktív játékainkkal várunk titeket! Látványos, szórakoztató, közérthető és átélhető módon mutatjuk be a természet törvényeit, a fizika csodálatos és meghökkentő világát – nem csak gyerekeknek. Interaktív tudományo'),
(722, 'Fizikai kísérletek minden nap a Csodák Palotájában', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Elektromosságtan, hőtan és mechanika témakörében tartunk izgalmas kísérlet bemutatókat az Öveges teremben, ahol gyakran a látogatók is részesei a demonstrációknak. A Fizika show-kon a legkülönfélébb fizikai – és olykor kémiai – kísérleteket vesszük elő.'),
(723, 'Budapest Bábszínház műsor 2024 / 2025. Előadások és online jegyvásárlás', '2024. december 1. (vasárnap) - 2024. december 8. (vasárnap) ', 48, 5, 'Budapest Bábszínház műsor 2024 / 2025. Online jegyvásárlás! A Budapest Bábszínház színvonalas gyermekműsorai mellett főleg felnőtt előadásairól vált híressé bel- és külföldön. A Budapest Bábszínház következetesen munkálkodik azon, hogy minden gyermekkoros'),
(724, 'Radnóti Színház előadások 2024 / 2025. Online jegyvásárlás', '2024. december 1. (vasárnap) - 2024. december 9. (hétfő) ', 48, 5, 'Radnóti Színház előadások 2024 / 2025. Online jegyvásárlás. A Radnóti Színház társulata kicsiny, mégis az ország egyik legerősebb szakmai társulása. A színház ápolja az irodalmi hagyományokat is, egy-egy költő életművét, egy mai szerzőt, egy folyóiratot, '),
(725, 'Rózsavölgyi Szalon előadások Budapest 2024 / 2025. Online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 7. (szombat) ', 48, 5, 'Rózsavölgyi Szalon előadások Budapest 2024 / 2025. Online jegyvásárlás. A zenemű- és könyvkiadással, hangversenyek szervezésével, zenei együttesek menedzselésével foglalkozó üzlet épülete fennállásának 100. évfordulójára a bolttal egybenyitva 2012. áprili'),
(726, 'Csokonai15 Kulturális Központ programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Budapesten a 15. kerületben, a Csokonai15 Kulturális Központ  meghatározó kulturális közösségi terei kiállításokkal, népzenei előadásokkal, táncházzal, gyermek- és felnőttprogramokkal, koncertekkel, családi mozidélelőttel, kvízműsorokkal, szabadegyetemmel'),
(727, 'Pestújhelyi Közösségi Ház programok 2024 Budapest', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Minőségi időtöltés, fejlődés, közösség és barátságos fogadtatás vár a Pestújhelyi Közösségi Házban. Műhelyeink, csoportjaink, képzéseink lehetővé teszik a folyamatos fejlődést és a kapcsolódást a kerületi lakosok igényei szerint. Baba-mama fejlesztés, mes'),
(728, 'Keszthelyi Balaton Színház programok 2024. Koncertek, hangversenyek, előadások, kiállítások', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 146, 5, 'A keszthelyi Balaton Színház Kulturális tevékenysége szerteágazó. Befogadó színházként több ezer elégedett bérletest láthatunk vendégül évről évre programok széles kínálatával. Hangversenyeinken, koncertjeinken számtalan híres és elismert hazai és külföld'),
(729, 'Budapesti koncert programok 2024 / 2025. Helyszínek, műsor, online jegyvásárlási lehetőség', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Budapesti koncert programok online jegyvásárlási lehetőséggel.'),
(730, 'Dumaszínház Budapest előadások 2024 / 2025. Online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Budapesti Dumaszínház előadások online jegyvásárlási lehetőséggel. A Dumaszínház Budapest esetében az ültetés a jegyvásárlás sorrendjében zajlik, tehát minél előbb vette meg a jegyét, annál jobb helyre szól az. A Dumaszínház Budapest jegyeinek ára az előa'),
(731, 'Dumaszínház előadások 2024 / 2025. Online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Dumaszínház előadások 2024 / 2025. Online jegyvásárlás. Már több, mint 60 klubban nevettetik a hálás közönséget egész évben, országszerte a humor nagyágyúi, a Dumaszínház művészei. Fellépéseik népszerűsége máig töretlen, előadásaik gyakran telt házzal ker'),
(732, 'Humorestek 2024 / 2025. Vidám műsorok, Dumaszínház előadások, online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 5, 'Vidám szórakoztató műsorok, humorestek, Dumaszínház előadások online jegyvásárlási lehetőséggel 2024-ben! Töltse vidáman az estéket a népszerű előadók műsoraival. Akár a fővárosban, akár vidéken, országszerte több előadás is várja a közönséget.'),
(733, 'Siófoki adventi programok 2024. Téli Varázs Siófokon', '2024.11.30. (szombat) - 2024.12.24. (kedd) ', 267, 6, 'Adventi programkavalkád  Siófok városában, hisz Siófok télen is varázslatos! Az idei évben is egy mesebeli Adventi időszakkal vár Siófok! Siófok és a Balaton téli varázsa idén is mindenkinek jár! Siófok idén decemberben is mindenki lelkét az ünnepekre han'),
(734, 'Alma Együttes koncertek 2024 / 2025. Fellépések, előadások műsornaptára', '2024. december 6. (péntek) ', 267, 6, 'Az Alma Együttes mára az egyik legkedveltebb zenekar a gyermekek körében. Koncertjeiken az egyedi stílusú etno zenét játszó együttes improvizatív módon kezeli a táncos-zenés együttlétet. A gyerekek, sőt a szülők is aktív részesei és formálói a sok vidámsá'),
(735, 'Gárdonyi Levendula workshop programok 2024. Alkossunk együtt adventi - karácsonyi ünnepi hangulatban', '2024. december 7. (szombat) ', 95, 6, 'Csatlakozz hozzánk különleges, kreatív workshop sorozatunkra! Minden, amit a workshopon használunk, természetes és környezetbarát alapanyagokkal és kellemes levendulaillatú környezetben. Neked semmit sem kell magaddal hoznod – minden alapanyagot és eszköz'),
(736, 'Zenekarácsony Békéscsaba 2024. Ünnepi szuperkoncertek sztárokkal kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 32, 6, 'Zenekarácsony, ünnepi koncertek Békéscsabán, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a'),
(737, 'Zenekarácsony Debrecen 2024. Karácsonyi sztárözön, ünnepi szuperkoncertek kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 62, 6, 'Zenekarácsony, ünnepi koncertek Debrecenben, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a');
INSERT INTO `esemeny` (`id`, `nev`, `datum`, `varosid`, `tipusid`, `leiras`) VALUES
(738, 'Zenekarácsony Szeged 2024. Ünnepi szuperkoncertek kicsiknek és nagyoknak karácsonyi hangulatban', '2024. december 26. (csütörtök) ', 277, 6, 'Zenekarácsony, ünnepi koncertek Szegeden, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit a hé'),
(739, 'Zenekarácsony Szombathely 2024. Ünnepi koncertek sztárokkal kicsiknek és nagyoknak', '2024. december 26. (csütörtök) ', 293, 6, 'Zenekarácsony, ünnepi koncertek Szombathelyen, ahol olyan programokat kínálunk, amiknek a színvonala, minősége, műfaja alkalmas arra, hogy a családtagok akár ajándékként is megvegyék ezekre a jegyet a szeretteiknek. Ha az ember ki akar szakadni egy kicsit'),
(740, 'Zenekarácsony koncertsorozat 2024. Várjuk Békéscsabán, Debrecenben, Szegeden és Szombathelyen', '2024. december 26. (csütörtök) - 2024. december 29. (vasárnap) ', 293, 6, 'Zenekarácsony koncertsorozat 2024. Ritkán adatik meg, hogy a karácsony 6 egymást követő munkaszüneti napot foglal magába. Úgy gondoltuk, hogy ez a pár nap alkalmas arra, hogy egy csokorba gyűjtsünk olyan top kategóriás produkciókat, amelyek igyekeznek min'),
(741, 'Agykontroll tanfolyam gyerekeknek 2024 / 2025', '2024. december 7. (szombat) - 2024. december 8. (vasárnap) ', 293, 6, 'A tanfolyam hatására a gyerek várhatóan magabiztosabb lesz, eredményesebben tud tanulni, képes megszüntetni fájdalmai zömét, betegség esetén gyorsabban meggyógyul, megtanulja céljait elérni, képes lesz megszabadulni rossz szokásaitól, képes jobb döntéseke'),
(742, 'Kezdőrúgás vásárlás az MTK Budapest hazai mérkőzéseire a 2024 / 2025-ös szezonban', '2024. december 14. (szombat) ', 48, 6, 'Vásárold meg hazai mérkőzéseinken a szurkolói kezdőrúgás meccsnapi élményét, és tiéd lehet az első passz a meccsen, amit a kedvenc játékosodnak is  adhatsz!  A kezdőrúgáshoz személyre szabott mez is jár egyedi feliratozással. A speaker is köszönt a jeles '),
(743, 'Bowling Debrecenben minden nap, szórakozás, aktív kikapcsolódás, sport, csapatépítés', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 62, 6, 'Debrecen kedvelt szórakoztató központjában 8 sávos, professzionális bowling pályával várunk.'),
(744, 'Mikulás rendelés 2024. Házhoz jön a Mikulás, és valóra váltja a gyermekek álmát', '2024. december 1. (vasárnap) - 2024. december 23. (hétfő) ', 48, 6, 'A Mikulás eljön, ha hívják! Mikulás szolgáltatásunk 2024. december 23-ig elérhető Budapesten és vonzáskörzetében. A családoknál és a cégeknél, valóra váltjuk a mesét, de az üzletekben is vevő csalogató lehet a megrendelt Mikulás.'),
(745, 'Budapesti kaland! Szabadtéri fergeteges kalandjáték csapatban, aktív élménydús kikapcsolódás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'Kapcsolódjatok ki egy fergeteges kalandjáték keretein belül, miközben megismerhetitek Budapest néhány nevezetességét. Töltsetek el néhány órát együtt, szerezzetek új élményeket! Programunk egy szabadtéren játszható csapatjáték, mely nyomozós, fejtörős, ka'),
(746, 'Kaposvár játék program, szabadtéri nyomozós, fejtörős, kalandos, rejtélyes és kalandos csapatjáték', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 136, 6, 'Fogd a mobilod és ismerd meg Kaposvárt egy kalandor szemével! Tölts el néhány órát a barátaid vagy családod társaságában! Kapcsolódjatok ki egy fergeteges kalandjáték keretein belül, miközben megismerhetitek Kaposvár néhány nevezetességét. Programunk egy '),
(747, 'Gokart pálya várja a száguldás szerelmeseit Budapesten, fedett pályás gokartozás minden évszakban', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'Az ASIA Gokart Center Budapest leghosszabb fedett gokart pályája, ami összesen 450 méter. Gokartjaink a francia Sodi márka kiemelkedő modelljei, melyek a legjobb beltérre tervezett gokartok. Mivel tulajdonképpen ezek adják a gokartozás legfőbb élményét, e'),
(748, 'Center Színház programok 2024 Budapest. Előadások kisebb és nagyobb gyerekeknek, családoknak', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'Előadások gyermekeknek, családoknak, óvodás és kisiskolás gyermekcsoportoknak. Mesejátékok, bábelőadások, gyerekkoncertek. Küldetésünk, hogy a gyermekek találkozhassanak a színházkultúrával. Törekszünk rá, hogy megmutassuk nekik és megszerettessük velük e'),
(749, 'Játszóház gyermekfelügyelettel, gondtalan budapesti családi bevásárlás gyerekekkel', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'A CipCirip Játszóház várja gyermekét, amíg Ön vásárol. A játszóházba 0-3 éves korig csak felnőtt kísérővel lehet tartózkodni. Amennyiben szeretné 3 évnél idősebb gyermekét nálunk hagyni, mi vigyázunk rá! Ennek egyetlen feltétele, hogy a gyermeknek ez alat'),
(750, 'MóKaland Játszóház programok szállóvendégeknek és külsős vendégeknek a Tisza Balneum Hotelben', '2024. december 6. (péntek) - 2024. december 8. (vasárnap) ', 305, 6, 'A Tisza Balneum Hotel MóKaland Játszóházát Tiszafüreden az apró szállóvendégeink és külsős vendégek is igénybe vehetik. A külsős vendégeknek a játszóház használatához Mókaland belépőjegy megváltása szükséges, amely szállodánk recepcióján vásárolható meg. '),
(751, 'Téli szüneti wellness pihenés animációs programokkal a Tisza-tónál, a Balneum Hotelben', '2025. január 2. (csütörtök) - 2025. január 5. (vasárnap) ', 305, 6, 'Töltse meghitt hangulatban téli pihenését a Tisza-tónál! Tegyenek egy sétát a Tiszavirág ártéri sétaúton, pihenjék ki az év fáradalmait wellness részlegünkön, lazító szauna rituáléinkon. A Balneum Hotel Téli szünet csomagja már 1 éjszakára foglalható félp'),
(752, 'Kaland program minden nap Gyulán, szabadulás a Kalandpincéből 60 perc alatt!', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 106, 6, 'Escape Room - Szabadulás a Pincéből 60 perc alatt! Izgalmas szabadulós játék, amely ijedelem nélkül biztosít felejthetetlen élményt mindenki számára. Kaland program minden nap Gyulán. A játék lényege, hogy egy berendezett, zárt pincéből fizikai erő haszná'),
(753, 'Budapest Bábszínház műsor 2024 / 2025. Előadások és online jegyvásárlás', '2024. december 1. (vasárnap) - 2024. december 8. (vasárnap) ', 48, 6, 'Budapest Bábszínház műsor 2024 / 2025. Online jegyvásárlás! A Budapest Bábszínház színvonalas gyermekműsorai mellett főleg felnőtt előadásairól vált híressé bel- és külföldön. A Budapest Bábszínház következetesen munkálkodik azon, hogy minden gyermekkoros'),
(754, 'Budapest séta programok 2024. Online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'Ismerje meg a várost, csatlakozzon a meghirdetett sétákhoz, városnézésekhez válasszon az izgalmas programok közül! Tematikus séták, változatos helyszínek, történelmi sztorik, fedezze fel a főváros titkait különleges programjainkon! Élményekben és látnival'),
(755, 'Garden of Lights Debrecen 2024 / 2025. Pinokkió multimédia-kiállítás, online jegyvásárlás', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 62, 6, 'Garden of Lights Debrecen 2024 / 2025. Online jegyvásárlás! Hurrá! Először Debrecenben a Garden of Lights varázslatos fény és multimédia-kiállítása, ahol elmerülhetünk a képzelet és a kreativitás erdejében! Az őszi, téli estéken szeretettel várunk Pinokki'),
(756, 'Garden of Lights Budapest 2024 / 2025. Hupikék Törpikék multimédia-kiállítás, online jegyek', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 6, 'Garden of Lights Budapest 2024 / 2025. Online jegyvásárlás! Hurrá! Végre újra Budapesten a Garden of Lights varázslatos fény és multimédia-kiállítása, ahol elmerülhetünk a képzelet és a kreativitás világában! Az őszi, téli estéken szeretettel várunk a Füv'),
(757, 'ISON Budapest 2024 / 2025. Programok és koncertek, online jegyvásárlás', '2024. december 5. (csütörtök) - 2024. december 6. (péntek) ', 48, 6, 'ISON programok, koncertek online jegyvásárlási lehetőséggel 2024 / 2025-ben. Közösségi tér, élőzenés szórakozóhely Erzsébetvárosban. Változatos kortárs koncertek, előadások zenei programok kerülnek megrendezésre.'),
(758, 'Diótörő előadások és jegyek 2024 / 2025. Online jegyvásárlás', '2024. december 5. (csütörtök) - 2024. december 8. (vasárnap) ', 48, 6, 'Diótörő előadások, vetítések, koncertek 2024 / 2025. A Diótörő, minden idők legnépszerűbb meséje, minden generációt képes elbűvölni és elgondolkoztatni arról, vajon beérhetjük-e a látszatvilággal, vagy a boldogság megtalálásához hinnünk kell abban, hogy m'),
(759, 'Budapesti orgonakoncertek 2024. Majestic Sounds orgonakoncertek a Belvárosi Szent Mihály templomban', '2024. december 6. (péntek) ', 48, 6, 'Budapesti Majestic Sounds orgonahangverseny-sorozat 2024. december 27-ig minden pénteken 19 órától. A koncertsorozat művészeti vezetője Teleki Miklós Artisjus-díjas orgona- és zongoraművész. A szóló koncerteken felváltva hangzik el egy barokk és egy roman'),
(760, 'Siófoki gyerekprogramok 2024 / 2025', '2024. december 6. (péntek) ', 267, 6, 'Gyermekprogramok Siófokon. Ünnepi gyermekelőadások, foglalkozások, rendezvények, fesztiválok egész évben Siófokon, a Balaton déli partjának kedvelt üdülőhelyén. Színes programkavalkád, mese és játék, kalózhajózás, gyermekszínház, játszóház várja a kicsike'),
(761, 'RaM - ArT Színház Budapest előadások és jegyvásárlás 2024 / 2025', '2024. december 6. (péntek) ', 48, 6, 'RaM - ArT Színház előadások Budapest első élményszínházában 2024 / 2025. A befogadó színházként működő helyszín a minőségi előadások bemutatását tűzte ki célul. Budapesti, vidéki társulatok egyaránt fellépnek az év során. Komoly és könnyűzenei koncertek, '),
(762, 'Cirkusz Budapest 2024 / 2025. Fővárosi Nagycirkusz előadások, online jegyvásárlás', '2024. december 6. (péntek) ', 48, 6, 'A méltán híres cirkusz minden új előadásával a nézők kedvében kíván járni. A magával ragadó műsorok kicsiknek és nagyoknak egyaránt felejthetetlen élményül szolgálnak. A hazai fellépők mellett rendszeresen külföldi fellépőkkel is találkozhat a nézőközönsé'),
(763, 'Karácsonyi program Budapesten, karácsonyi vacsora sétahajózással és élőzenével', '2024. december 24. (kedd)  19:00', 48, 7, 'Ha szeretné egy különleges, és meghitt karácsonyi hangulatban tölteni a téli ünnepeket akkor a karácsonyi varázzsal átitatott Gróf Széchenyi hajón a helye. Töltsük együtt ezt a meghitt és békés adventi időszakot!'),
(764, 'Kávéház program Budapest 2024. Térjen be egy finom kávéra a Atryum  Fashion Cafe Barba!', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 7, 'Térjen be egy finom kávéra Budapest belvárosában az Atrium Fashion City bevásárlóközpontban található Atryum Fashion Café Bárba. Állatbarát kávézónkban hétről-hétre más-más akcióval várjuk kedves vendégeinket. A kávéház kiváló lehetőséget biztosít arra is'),
(765, 'Zene és Bor 2024. A 100 tagú Cigányzenekar ünnepi koncertje vacsorával és borkóstolóval Budapesten', '2024. december 30. (hétfő) ', 48, 7, 'Már hagyománnyá vált a 2024-ben 28. alkalommal megrendezésre kerülő ZENE-BOR ünnepe, melyen minden évben december 30-án nagyszabású gálakoncertet ad a világon egyedül álló 100 Tagú Cigányzenekar. Kétrészes műsoruk repertoárján a virtuóz cigányzene, a jól '),
(766, 'Egri Borszalon 2024', '2024. december 29. (vasárnap) ', 78, 7, 'Borászok és boraik társaságában zárjuk és búcsúztatjuk a 2024-es évet. Már 22. éve ezen a napon rendezzük meg az Egri Borszalont, napra pontosan 3 estével Szilveszter előtt. Lépj be a húszas évek pezsgő világába és légy részese Eger legelegánsabb évzáró ü'),
(767, 'Budafoki Pincejárat 2024. Nyitott pincék minden hónap első szombatján', '2024. december 7. (szombat) ', 48, 7, 'Budafoki pincejárat 2024-ben is! Fedezze fel velünk a Bornegyedet, nyitott pincék Budapesten - igazi borélmény minden hónap első szombatján. Borkóstolók, kiállítások és könnyűzenei programok. Budapest Bornegyedében számtalan neves pezsgőkészítő cég és bor'),
(768, 'Pécsi sörtúra 2024. Izgalmas sörfőzde gyárlátogatás felejthetetlen sörkóstolással minden szombaton', '2024. december 7. (szombat) ', 235, 7, 'Fedezd fel a Pécsi Sörfőzdét! Pécsi sörtúra programunk keretében meghívunk egy izgalmas gyárlátogatásra, ahol betekinthetsz a Pécsi Sörfőzde működésébe, a sörkészítés folyamatába és megismerheted a sör alapanyagait is, összekötve egy felejthetetlen sörkós'),
(769, 'Szilveszteri vacsora Budapest 2024. Gatsby Szilveszter élőzenével a Vogue hajón', '2024. december 31. (kedd) ', 48, 7, 'Szilveszteri vacsora Budapesten a Vogue Hajón 2024. december 31-én. Készülj egy lenyűgöző éjszakára Budapest leghangulatosabb állóhajóján! Köszöntsük együtt a 2025-ös esztendőt egy hamisítatlan Gatsby-stílusú szilveszteri bulin! Idén több, mint 100 évet u'),
(770, 'Macaron workshop 2024 Győr. Tanuld meg a macaronsütés csínját-bínját egy profitól!', '2024. december 6. (péntek) ', 105, 7, 'A cukrászat világában a francia stílus hódítani kezd Magyarországon is. Könnyed, csábító és frappáns ízvilágával egyre többeket rabul ejt, és mára már divattá váltak a francia sütemények. Ezek királynője a jól ismert, ám annál összetettebb macaron. Sütése'),
(771, 'Sütemény workshop 2024 / 2025. Győr. Süss, alkoss, sütemény készítő kurzusok', '2024. december 6. (péntek) ', 105, 7, 'Sütemény készítő workshop a sütés szerelmeseinek! Tanfolyamainkon különféle stílusok és ízek között lehet válogatni: torták, hagyományos rétesek, vegán, klasszikus és monodesszertek, sütemények. Változatos tanfolyamaink között minden gyermek és felnőtt me'),
(772, 'Liliomkert termelői piac Káptalantóti 2024', '2024. december 8. (vasárnap) ', 105, 7, 'A Káli-medence szívében fellelhető termelői piacot Harmathy Ildikó biológus-mérnök álmodta meg és hozta létre. Jól teszi, aki a vasárnaponkénti káptalantóti piacra üres hassal érkezik, mert képtelenség megállni, hogy a helyi termelők asztalkái közt járva '),
(773, 'Borhajó Budapesten, élőzenés sétahajózás borkóstolóval, ínyencségekkel 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 7, 'Lépjen fedélzetünkre és ismerje meg a várost a lehető legszebb perspektívából. A Duna vizéről Budapest leggyönyörűbb látványosságai tárulnak a szeme elé, mint a Parlament, a Bazilika vagy a Nagy Vásárcsarnok. A folyó túloldalán feltekinthet a lélegzetelál'),
(774, 'Karácsonyi menü ajánlat a hévízi Brix Bistroban céges vacsorához', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 119, 7, 'KARÁCSONYI VACSORA AJÁNLATUNK - Tartsa különleges környezetben céges karácsonyi eseményét és válassza szállodánk Brix Bistroját, ahol magas színvonalú, professzionális szolgáltatásokat és kiváló gasztronómiai kínálatot nyújtunk Önnek és csapatának!'),
(775, 'Gasztro hétvége Hévízen, pálinkakóstolóval a Bonvital Wellness & Gastro Hotelben', '2024. december 6. (péntek) - 2024. december 8. (vasárnap) ', 119, 7, 'A Bonvital Wellness & Gasztro felnőttbarát szállodában változatos gasztro programokkal várják a vendégeket minden hónapban egy-egy hétvégén Hévízen. 2024. december 6-án este pálinkakóstoló lesz bemutatóval és ízletes falatkákkal. A programhoz foglaljon sz'),
(776, 'Gyulai Mézfesztivál szállással a Wellness Hotel Gyula szállodában', '2024. december 14. (szombat) - 2024. december 15. (vasárnap) ', 106, 7, 'Gyulai Mézesztivál 2024. december 14-15-én. Ezen a két napon mézeskalácsok, cukrászati különlegességek bemutatása, kóstolása és vására várja a látogatókat. A fesztivál idejére foglaljon szállást a négycsillagos Wellness Hotel Gyulában, csomagjaink teljes '),
(777, 'Grillkirály programok 2024. Események, rendezvények, fesztiválok, ahol találkozhattok velünk', '2024.11.29. (péntek) - 2024.12.22. (vasárnap) ', 106, 7, 'A legfinomabb grillételekkel várunk mindenkit szeretettel különböző rendezvényeken, fesztiválokon a Grillkirály standján. Kulináris élmények, gasztronómiai finomságok, grilltálak, hagyományos ízek és ételek várják a Grillkirály programjain az érdeklődőket'),
(778, 'Palacsintafesztivál 2024 Balatonalmádi. Palacsinta, Kolbász és Mikulásfesztivál Almádiban', '2024. december 6. (péntek) - 2024. december 12. (csütörtök) ', 18, 7, 'Várunk mindenkit szeretettel a Balaton legszebb karácsonyi vásárába, ahol Palacsinta, Kolbász és Mikulásfesztivál várja a látogatókat 2024. december 6 és 12 között. Hatalmas jégpálya is üzemel, ami a vásár alatt nyitva tart. A belépés ingyenes és kutyabar'),
(779, 'Bortúra Mór 2024. We Love Mór Bortúra szállással az Öreg Prés Butikhotelben', '2024. december 28. (szombat) ', 198, 7, 'Bortúrára vár az Öreg Prés Butikhotel Móron! Még van szabad szobánk… Jöhetsz egyedül - egyágyas szobáink kényelmesek, és tökéletesek számodra. Jöhettek kettesben-romantikus hangulatú szobáinkban visszarepültök az időben. Jöhettek az egész családdal-apartm'),
(780, 'Szilveszter egy igazi falusi disznóvágással és borvacsorával a Fenyőharaszt Kastélyszállóban', '2024.12.29. (vasárnap) - 2025.01.01. (szerda) ', 198, 7, 'Ha Ön is szeretné, hogy emlékezetes legyen az „évforduló”, vegyen velünk részt egy igazi, falusi, felejthetetlen disznóvágáson, ahol lesz minden, ami a vacogó téli hidegben felpezsdíti az ember vérét: pálinka, forralt bor, cigányzene, pogácsa és finom étk'),
(781, 'Karácsonyi menü Tata, rendelje meg a karácsonyi ebédet vagy vacsorát a Veranda Bistro & More-ból!', '2024.11.28. (csütörtök) - 2024.12.20. (péntek) ', 299, 7, 'Karácsonyi menü Tatán, ünnepi elviteles tálak a Veranda Bistro & More-ban. Ünnepelje a karácsonyt szeretteivel és bízza ránk a karácsonyi lakomát! Chefünk által készített ünnepi ételekkel tegye különlegessé az idei Karácsonyt! Rendelje meg tőlünk a Karács'),
(782, 'Karácsonyi céges vacsora Tatán, a Veranda Bistro & More-ban', '2024. december 1. (vasárnap) - 2024. december 23. (hétfő) ', 299, 7, 'Céges karácsonyi vacsora Tatán, a Veranda Bistro & More-ban. Nem tudja, hol tartsa a céges karácsonyi vacsorát? Szeretné lezárni az évet finom ételek mellett, jó hangulatban? Svédasztal, bőségtálak, hidegtálak, italok az alapja egy remek céges bulinak. Le'),
(783, 'Borhajó Budapesten, élőzenés sétahajózás borkóstolóval, ínyencségekkel 19:00 órától - JEGYVÁSÁRLÁS', '2024. december 6. (péntek)  19:00', 48, 7, 'Lépjen fedélzetünkre és ismerje meg a várost a lehető legszebb perspektívából. A Duna vizéről Budapest leggyönyörűbb látványosságai tárulnak a szeme elé, mint a Parlament, a Bazilika vagy a Nagy Vásárcsarnok. A folyó túloldalán feltekinthet a lélegzetelál'),
(784, 'Szindbád Nyíregyháza 2024. Programok és vetítések, online jegyvásárlás', '2024. december 10. (kedd) - 2024. december 11. (szerda) ', 216, 7, 'Szindbád Színháztörténeti Rendezvénytér programok online jegyvásárlási lehetőséggel 2024-ben. Nyíregyháza kulturális negyedének egyik új és izgalmas közösségi tere filmvetítésekkel, programokkal várja a látogatókat. A Szindbád VIP Mozi all inclusive mozié'),
(785, 'Karácsonyi program Budapesten, karácsonyi vacsora sétahajózással és élőzenével', '2024. december 24. (kedd)  19:00', 48, 7, 'Ha szeretné egy különleges, és meghitt karácsonyi hangulatban tölteni a téli ünnepeket akkor a karácsonyi varázzsal átitatott Gróf Széchenyi hajón a helye. Töltsük együtt ezt a meghitt és békés adventi időszakot!'),
(786, 'Zene és Bor 2024. A 100 tagú Cigányzenekar ünnepi koncertje vacsorával és borkóstolóval Budapesten', '2024. december 30. (hétfő) ', 48, 7, 'Már hagyománnyá vált a 2024-ben 28. alkalommal megrendezésre kerülő ZENE-BOR ünnepe, melyen minden évben december 30-án nagyszabású gálakoncertet ad a világon egyedül álló 100 Tagú Cigányzenekar. Kétrészes műsoruk repertoárján a virtuóz cigányzene, a jól '),
(787, 'Kezdőrúgás vásárlás az MTK Budapest hazai mérkőzéseire a 2024 / 2025-ös szezonban', '2024. december 14. (szombat) ', 48, 8, 'Vásárold meg hazai mérkőzéseinken a szurkolói kezdőrúgás meccsnapi élményét, és tiéd lehet az első passz a meccsen, amit a kedvenc játékosodnak is  adhatsz!  A kezdőrúgáshoz személyre szabott mez is jár egyedi feliratozással. A speaker is köszönt a jeles '),
(788, 'Pécsi sörtúra 2024. Izgalmas sörfőzde gyárlátogatás felejthetetlen sörkóstolással minden szombaton', '2024. december 7. (szombat) ', 235, 8, 'Fedezd fel a Pécsi Sörfőzdét! Pécsi sörtúra programunk keretében meghívunk egy izgalmas gyárlátogatásra, ahol betekinthetsz a Pécsi Sörfőzde működésébe, a sörkészítés folyamatába és megismerheted a sör alapanyagait is, összekötve egy felejthetetlen sörkós'),
(789, 'Törley Pezsgőmanufaktúra és Látogatóközpont csoportos látogatás Budapesten', '2024. december 2. (hétfő) - 2024. december 6. (péntek) ', 48, 8, 'A Törley pezsgők története majdnem másfél évszázadra nyúlik vissza. Ezt a sokszínű, időnként nehéz, de egyúttal sikeres 140 évet meséli el nekünk a Törley Gyűjtemény és Látogatóközpont. Egyénileg érkező látogatók számára a Törley Gyűjtemény és Látogatóköz'),
(790, 'Retro Party Budapesten, minden héten reggelig nosztalgiázunk a 80’s - 90’s évek legtutibb slágereire', '2024. december 6. (péntek) - 2024. december 7. (szombat) ', 48, 8, 'Nézzetek be hozzánk, hiszen minden PÉNTEKEN és SZOMBATON hamisítatlan Retro Partyval vár Retro Táncterünk! A legtutibb slágerek csendülnek fel Dj-ink vezényletével a 80’s-90’s évekből! Minden héten reggelig nosztalgiázunk megismételhetetlen táncmozdulatok'),
(791, 'Családi nap Budán 2024. Adventi családi ünnep a Budavári Palotanegyedben', '2024. december 22. (vasárnap) ', 48, 8, 'Merülj el az adventi várakozás varázslatában a Várkert Bazárban, ahol december 22-én egész napos adventi családi rendezvénnyel várjuk a családokat! Hozd el gyermekeidet és éljetek át egy meghitt napot közösen, ahol minden pillanat az ünnepi készülődés örö'),
(792, 'Esküvő Kiállítás Szeged 2025. Menyegző Esküvő Kiállítás az IH Rendezvényközpontban', '2025. január 4. (szombat) ', 277, 8, '2025-ben jön a XVIII. Menyegző Esküvő Kiállítás, Szeged és a dél-alföldi régió legnagyobb és legszínvonalasabb Esküvői kiállítása! Ezen a szombaton találkozhatsz kiállítóinkkal, köztük menyasszonyi ruhaszalonok, esküvői helyszínek és vendéglátósok képvise'),
(793, 'Esküvő Kiállítás Kecskemét 2025. Találkozz az esküvő szakma nagyjaival és minőségi kiállítóival!', '2025. február 2. (vasárnap) ', 141, 8, '26. Kecskeméti Esküvő Kiállítás a szakma nagyjaival! Várjuk szeretettel az ifjú párokat és az újabb minőségi kiállítókat ezen a gyönyörű helyszínen. Minőségi szolgáltatók, ÓRIÁSI kedvezmények! Bemutatkoznak a helyi és környékbeli esküvői szolgáltatók, itt'),
(794, 'Bowling Debrecenben minden nap, szórakozás, aktív kikapcsolódás, sport, csapatépítés', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 62, 8, 'Debrecen kedvelt szórakoztató központjában 8 sávos, professzionális bowling pályával várunk.'),
(795, 'Mikulás rendelés 2024. Házhoz jön a Mikulás, és valóra váltja a gyermekek álmát', '2024. december 1. (vasárnap) - 2024. december 23. (hétfő) ', 48, 8, 'A Mikulás eljön, ha hívják! Mikulás szolgáltatásunk 2024. december 23-ig elérhető Budapesten és vonzáskörzetében. A családoknál és a cégeknél, valóra váltjuk a mesét, de az üzletekben is vevő csalogató lehet a megrendelt Mikulás.'),
(796, 'Karácsonyi céges vacsora Tiszafüreden a Balneum Hotelben', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 305, 8, 'Karácsonyi céges vacsora Tiszafüreden a Balneum Hotelben. Szeretnédmegköszönni kollégáinak egész éves munkájukat? Mi garantáljuk, hogy az évzáró vacsorára a legjobb helyszín a Tisza Balneum Hotel****! Használják ki az év utolsó perceit és értékeljék ki ná'),
(797, 'Bicikli kalandok Budapesten izgalmas fejtörőkkel, kerékpáros élményprogramok csodálatos helyeken', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 8, 'Kalandra fel, várnak a játékos kerékpáros szabadtéri élményprogramok Budapesten! Egy-egy küldetést végigjátszva Budapest legcsodálatosabb helyeit fedezheted fel úgy, hogy közben izgalmas fejtörőket kell megoldani. Feladványok fogják nehezíteni a kalandoda'),
(798, 'Budapesti kalandok a szabadban izgalmas fejtörőkkel, élményjáték programok csodálatos helyeken', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 48, 8, 'Kalandra fel, vár sok játékos budapesti szabadtéri élményprogram! Egy-egy küldetést végigjátszva Budapest legcsodálatosabb helyeit fedezheted fel úgy, hogy közben izgalmas fejtörőket kell megoldani. Feladványok fogják nehezíteni a kalandodat, amelyek hely'),
(799, 'Kaland Tatán izgalmas fejtörőkkel a ravasz szörnyek nyomában, csodálatos helyszíneken', '2024. december 2. (hétfő) - 2024. december 8. (vasárnap) ', 299, 8, 'Kalandra fel, játékos szabadtéri élményprogram Tatán! A küldetést végigjátszva Tata legcsodálatosabb helyeit fedezheted fel úgy, hogy közben izgalmas fejtörőket kell megoldani. Feladványok fogják nehezíteni a kalandodat, amelyek helyenként igazi kihívások'),
(800, 'Céges karácsonyi buli panorámás pincénkben a Strázsa-hegyi kilátónál, várjuk a Monori Pincefaluban', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 197, 8, 'Tartsák céges karácsonyi buli rendezvényüket Monori Pincefalunkban, a Strázsa-hegyi kilátó szomszédságában található Petrovai Pincénkben! Teraszos pincénkhez családias hangulatú rendezvényház is tartozik, ahol 20 főtől vállaljuk kisebb és nagyobb emlékeze'),
(801, 'Karácsonyi menü ajánlat a hévízi Brix Bistroban céges vacsorához', '2024. december 1. (vasárnap) - 2024. december 22. (vasárnap) ', 119, 8, 'KARÁCSONYI VACSORA AJÁNLATUNK - Tartsa különleges környezetben céges karácsonyi eseményét és válassza szállodánk Brix Bistroját, ahol magas színvonalú, professzionális szolgáltatásokat és kiváló gasztronómiai kínálatot nyújtunk Önnek és csapatának!'),
(802, 'Grillkirály programok 2024. Események, rendezvények, fesztiválok, ahol találkozhattok velünk', '2024.11.29. (péntek) - 2024.12.22. (vasárnap) ', 119, 8, 'A legfinomabb grillételekkel várunk mindenkit szeretettel különböző rendezvényeken, fesztiválokon a Grillkirály standján. Kulináris élmények, gasztronómiai finomságok, grilltálak, hagyományos ízek és ételek várják a Grillkirály programjain az érdeklődőket'),
(803, 'Céges Karácsony Móron az Öreg Prés Butikhotelben', '2024. december 1. (vasárnap) - 2024. december 29. (vasárnap) ', 198, 8, 'Karácsonyi céges rendezvények az Öreg Présben Móron. Az év vége közeledtével fontos együtt ünnepelni a kollégákkal, lezárni az évet, hogy aztán az egész csapat újult erővel induljon neki a munkának januárban.  Különtermeink kiválóak egy kellemes vacsora v'),
(804, 'Családi nap Budán 2024. Adventi családi ünnep a Budavári Palotanegyedben', '2024. december 22. (vasárnap) ', 48, 8, 'Merülj el az adventi várakozás varázslatában a Várkert Bazárban, ahol december 22-én egész napos adventi családi rendezvénnyel várjuk a családokat! Hozd el gyermekeidet és éljetek át egy meghitt napot közösen, ahol minden pillanat az ünnepi készülődés örö');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `esemeny`
--
ALTER TABLE `esemeny`
  ADD PRIMARY KEY (`id`),
  ADD KEY `helyszin` (`varosid`),
  ADD KEY `tipusid` (`tipusid`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `esemeny`
--
ALTER TABLE `esemeny`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=805;

--
-- Megkötések a kiírt táblákhoz
--

--
-- Megkötések a táblához `esemeny`
--
ALTER TABLE `esemeny`
  ADD CONSTRAINT `esemeny_ibfk_1` FOREIGN KEY (`varosid`) REFERENCES `varos` (`id`),
  ADD CONSTRAINT `esemeny_ibfk_2` FOREIGN KEY (`tipusid`) REFERENCES `tipus` (`tipus_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
